import {BARCODE_SCANNED, BARCODE_SCANNING, ENABLE_BARCODE_SCANNER, DISABLE_BARCODE_SCANNER} from "@constants/actions";

export default {
    BARCODE_SCANNING,
    BARCODE_SCANNED,
    DISABLE_BARCODE_SCANNER,
    ENABLE_BARCODE_SCANNER
}
